/**
 * Generated by orval v8.0.0-rc.6 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import type { HealthResponseServices } from './healthResponseServices';
import type { HealthResponseStatus } from './healthResponseStatus';

/**
 * Health check response with detailed service statuses.
 */
export interface HealthResponse {
  status: HealthResponseStatus;
  version?: string;
  services: HealthResponseServices;
}
