/**
 * Generated by orval v8.0.0-rc.6 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import type { ServiceStatus } from './serviceStatus';

export type HealthResponseServices = {[key: string]: ServiceStatus};
