/**
 * Generated by orval v8.0.0-rc.6 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export type ServiceStatusStatus = typeof ServiceStatusStatus[keyof typeof ServiceStatusStatus];


export const ServiceStatusStatus = {
  healthy: 'healthy',
  unhealthy: 'unhealthy',
} as const;
