/**
 * Generated by orval v8.0.0-rc.6 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import type { ServiceStatusStatus } from './serviceStatusStatus';

/**
 * Individual service health status.
 */
export interface ServiceStatus {
  status: ServiceStatusStatus;
  latency_ms?: number | null;
  error?: string | null;
}
