// Generated by design-tokens package - DO NOT EDIT MANUALLY
// ignore_for_file: type=lint

import 'dart:ui' show Color, ColorSpace;

import 'package:forui/forui.dart';

final generatedLightTheme = FThemes.zinc.light.copyWith(
  colors: FThemes.zinc.light.colors.copyWith(
    barrier: Color.from(alpha: 1.000, red: 0.8956, green: 0.8956, blue: 0.8956, colorSpace: ColorSpace.displayP3),
    background: Color.from(alpha: 1.000, red: 1.0000, green: 1.0000, blue: 1.0000, colorSpace: ColorSpace.displayP3),
    foreground: Color.from(alpha: 1.000, red: 0.0394, green: 0.0394, blue: 0.0394, colorSpace: ColorSpace.displayP3),
    primary: Color.from(alpha: 1.000, red: 0.6909, green: 0.8958, blue: 0.3768, colorSpace: ColorSpace.displayP3),
    primaryForeground: Color.from(alpha: 1.000, red: 0.0660, green: 0.1015, blue: 0.0158, colorSpace: ColorSpace.displayP3),
    secondary: Color.from(alpha: 1.000, red: 0.9606, green: 0.9606, blue: 0.9606, colorSpace: ColorSpace.displayP3),
    secondaryForeground: Color.from(alpha: 1.000, red: 0.0394, green: 0.0394, blue: 0.0394, colorSpace: ColorSpace.displayP3),
    muted: Color.from(alpha: 1.000, red: 0.9606, green: 0.9606, blue: 0.9606, colorSpace: ColorSpace.displayP3),
    mutedForeground: Color.from(alpha: 1.000, red: 0.4447, green: 0.4447, blue: 0.4447, colorSpace: ColorSpace.displayP3),
    destructive: Color.from(alpha: 1.000, red: 0.7622, green: 0.1732, blue: 0.1559, colorSpace: ColorSpace.displayP3),
    destructiveForeground: Color.from(alpha: 1.000, red: 0.9803, green: 0.9803, blue: 0.9803, colorSpace: ColorSpace.displayP3),
    error: Color.from(alpha: 1.000, red: 0.7622, green: 0.1732, blue: 0.1559, colorSpace: ColorSpace.displayP3),
    errorForeground: Color.from(alpha: 1.000, red: 0.9803, green: 0.9803, blue: 0.9803, colorSpace: ColorSpace.displayP3),
    border: Color.from(alpha: 1.000, red: 0.8956, green: 0.8956, blue: 0.8956, colorSpace: ColorSpace.displayP3),
    hoverLighten: 0.075,
    hoverDarken: 0.05,
    disabledOpacity: 0.5,
  ),
);

final generatedDarkTheme = FThemes.zinc.dark.copyWith(
  colors: FThemes.zinc.dark.colors.copyWith(
    barrier: Color.from(alpha: 0.100, red: 1.0000, green: 1.0000, blue: 1.0000, colorSpace: ColorSpace.displayP3),
    background: Color.from(alpha: 1.000, red: 0.0394, green: 0.0394, blue: 0.0394, colorSpace: ColorSpace.displayP3),
    foreground: Color.from(alpha: 1.000, red: 0.9803, green: 0.9803, blue: 0.9803, colorSpace: ColorSpace.displayP3),
    primary: Color.from(alpha: 1.000, red: 0.6909, green: 0.8958, blue: 0.3768, colorSpace: ColorSpace.displayP3),
    primaryForeground: Color.from(alpha: 1.000, red: 0.0660, green: 0.1015, blue: 0.0158, colorSpace: ColorSpace.displayP3),
    secondary: Color.from(alpha: 1.000, red: 0.1315, green: 0.1315, blue: 0.1315, colorSpace: ColorSpace.displayP3),
    secondaryForeground: Color.from(alpha: 1.000, red: 0.9803, green: 0.9803, blue: 0.9803, colorSpace: ColorSpace.displayP3),
    muted: Color.from(alpha: 1.000, red: 0.1315, green: 0.1315, blue: 0.1315, colorSpace: ColorSpace.displayP3),
    mutedForeground: Color.from(alpha: 1.000, red: 0.6205, green: 0.6205, blue: 0.6205, colorSpace: ColorSpace.displayP3),
    destructive: Color.from(alpha: 1.000, red: 0.6042, green: 0.0452, blue: 0.0663, colorSpace: ColorSpace.displayP3),
    destructiveForeground: Color.from(alpha: 1.000, red: 0.9803, green: 0.9803, blue: 0.9803, colorSpace: ColorSpace.displayP3),
    error: Color.from(alpha: 1.000, red: 0.6042, green: 0.0452, blue: 0.0663, colorSpace: ColorSpace.displayP3),
    errorForeground: Color.from(alpha: 1.000, red: 0.9803, green: 0.9803, blue: 0.9803, colorSpace: ColorSpace.displayP3),
    border: Color.from(alpha: 0.100, red: 1.0000, green: 1.0000, blue: 1.0000, colorSpace: ColorSpace.displayP3),
    hoverLighten: 0.075,
    hoverDarken: 0.05,
    disabledOpacity: 0.5,
  ),
);
