project:
  name: fullstack-starter
  description: Modern fullstack monorepo template with Next.js 16, FastAPI, Flutter, and GCP infrastructure

structure:
  monorepo: true
  apps:
    - name: api
      path: apps/api
      language: python
      framework: fastapi
      description: FastAPI backend with PostgreSQL, Redis, and async SQLAlchemy

    - name: web
      path: apps/web
      language: typescript
      framework: nextjs
      description: Next.js 16 frontend with React 19, TailwindCSS v4, and shadcn/ui

    - name: worker
      path: apps/worker
      language: python
      framework: fastapi
      description: Background worker for Cloud Tasks and Pub/Sub

    - name: mobile
      path: apps/mobile
      language: dart
      framework: flutter
      description: Flutter mobile app with Riverpod and go_router

    - name: infra
      path: apps/infra
      language: hcl
      framework: terraform
      description: GCP infrastructure with Terraform

  packages:
    - name: design-tokens
      path: packages/design-tokens
      description: Shared design tokens (Source of Truth)
    - name: i18n
      path: packages/i18n
      description: Shared i18n package (Source of Truth)

conventions:
  naming:
    files: kebab-case
    components: PascalCase
    functions: camelCase
    python_functions: snake_case
    constants: SCREAMING_SNAKE_CASE

  code_style:
    typescript:
      formatter: biome
      linter: biome
      config: biome.json
    python:
      formatter: ruff
      linter: ruff
      config: ruff.toml
    dart:
      analyzer: dart_analyzer
      config: analysis_options.yaml
    terraform:
      formatter: terraform fmt

  testing:
    web:
      unit: vitest
      e2e: playwright
    api:
      unit: pytest
      async: pytest-asyncio
    mobile:
      unit: flutter_test
      integration: integration_test

tools:
  runtime_manager: mise
  package_managers:
    javascript: pnpm
    python: uv
    dart: pub
  task_runners:
    javascript: pnpm scripts
    python: poe (poethepoet)
    dart: flutter commands

commands:
  install:
    root: pnpm install
    api: uv sync --frozen
    web: pnpm install
    worker: uv sync --frozen
    mobile: flutter pub get

  dev:
    api: poe dev
    web: pnpm dev
    worker: poe dev
    mobile: flutter run

  build:
    root: pnpm build
    api: docker build -t api .
    web: pnpm build
    worker: docker build -t worker .
    mobile: flutter build

  test:
    root: pnpm test
    api: poe test
    web: pnpm test
    worker: poe test
    mobile: flutter test

  lint:
    root: pnpm lint
    api: poe lint
    web: pnpm lint
    mobile: flutter analyze

  format:
    root: pnpm format
    api: poe format
    mobile: dart format .

important_files:
  - mise.toml: Runtime versions and task runner
  - biome.json: JS/TS linting and formatting
  - pnpm-workspace.yaml: pnpm workspace configuration
  - apps/api/pyproject.toml: Python dependencies and tasks
  - apps/api/docker-compose.infra.yml: Local infrastructure (PostgreSQL, Redis, MinIO)
  - apps/web/package.json: Web dependencies and scripts
  - apps/infra/variables.tf: Infrastructure configuration

documentation:
  - .agent/rules/GEMINI.md: Project overview for AI agents
  - .agent/rules/build-guide.md: Build and deployment guide
  - .agent/rules/lint-format-guide.md: Linting and formatting guide
  - .agent/rules/test-guide.md: Testing guide
